
# --- Build options configuration

# Brief output during build process
BRIEF_OUTPUT=1

# Build for debugging
DEBUG=1

# Build optimized
#OPT=1

# Index base
BASE=1

# USE BLAS for basic linear algebra
# Use of double required for BLAS in the current version of ulmsp
# For CBLAS specify the lib name in system.inc or use OPENBLAS
#USE_BLAS=1
#USE_CBLAS=1
#USE_OPENBLAS=1

# Print more output for some routines
VERBOSE=1
